// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package bustimerkic

import (
	"database/sql"
)

type BusstopUrl struct {
	ID          int64
	Busstop     sql.NullString
	Busname     sql.NullString
	Destination sql.NullString
	Url         sql.NullString
}
