version: '3.3'

services:
  waveinfo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 10000:8080
    volumes:
      - ./waveinfo:/app/src
  mongodb:
    image: mongo:latest
    container_name: bustimer_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: bustimer_mongo_express
    restart: always
    ports:
      - 10001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
volumes:
  mongodb_data: