package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"github.com/mercy34mercy/bustimer_kic/bff/graph/model"
	"github.com/mercy34mercy/bustimer_kic/bff/repository"
)

// TimeTable is the resolver for the TimeTable field.
func (r *queryResolver) TimeTable(ctx context.Context, fr string, to string) (*model.TimeTable, error) {
	tRepository := repository.NewTimetableRepository()

	timetable, err := tRepository.FindTimetable(fr, to)
	if err != nil {
		return nil, err
	}
	return timetable, err
}

// ApproachInfo is the resolver for the ApproachInfo field.
func (r *queryResolver) ApproachInfo(ctx context.Context, fr string, to string) (*model.ApproachInfos, error) {
	aRepository := repository.NewApproachInfoRepository()

	approachInfos, err := aRepository.FindApproachInfo(fr, to)

	if err != nil {
		return nil, err
	}
	return approachInfos, err
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
