package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	graph "github.com/mercy34mercy/bustimer_kic/bff/graph/genarated"
	"github.com/mercy34mercy/bustimer_kic/bff/graph/model"
)

// TimeTable is the resolver for the TimeTable field.
func (r *queryResolver) TimeTable(ctx context.Context, fr string, to string) (*model.TimeTable, error) {
	panic(fmt.Errorf("not implemented: TimeTable - TimeTable"))
}

// ApproachInfo is the resolver for the ApproachInfo field.
func (r *queryResolver) ApproachInfo(ctx context.Context, fr string, to string) (*model.ApproachInfos, error) {
	panic(fmt.Errorf("not implemented: ApproachInfo - ApproachInfo"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
