// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ApproachInfo struct {
	MoreMin        string `json:"MoreMin"`
	RealARivalTime string `json:"RealARivalTime"`
	Direction      string `json:"Direction"`
	ScheduledTime  string `json:"ScheduledTime"`
	Delay          string `json:"Delay"`
	BusStop        string `json:"BusStop"`
	BusName        string `json:"BusName"`
	RequiredTime   int    `json:"RequiredTime"`
}

type ApproachInfos struct {
	ApproachInfo []*ApproachInfo `json:"ApproachInfo"`
}

type MultiTimeTable struct {
	TimeTable []*MultiTimeTableMap `json:"TimeTable"`
}

type MultiTimeTableMap struct {
	Key   string     `json:"key"`
	Value *TimeTable `json:"value"`
}

type OneBusTime struct {
	BusName string `json:"BusName"`
	Min     string `json:"Min"`
	BusStop string `json:"BusStop"`
}

type TimeTable struct {
	TimeTable []*TimeTable `json:"TimeTable"`
}

type TimetableMap struct {
	Key   int         `json:"key"`
	Value *OneBusTime `json:"value"`
}
